# Generated by Django 4.1.7 on 2023-03-03 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Student', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
