# Generated by Django 4.1.7 on 2023-03-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assignment_alter_question_text_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ManyToManyField(related_name='student_assignment', to='courses.student'),
        ),
    ]
