# Generated by Django 4.1.7 on 2023-03-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_number',
            field=models.IntegerField(default=0),
        ),
    ]
